"""empty message

Revision ID: 3cd27a5e41b6
Revises: 98eb5c7ba933
Create Date: 2016-01-14 07:26:45.096832

"""

# revision identifiers, used by Alembic.
revision = '3cd27a5e41b6'
down_revision = '98eb5c7ba933'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('good', sa.String(length=100), nullable=True),
    sa.Column('bad', sa.String(length=100), nullable=True),
    sa.Column('count', sa.String(length=100), nullable=True),
    sa.Column('text', sa.String(length=10000), nullable=True),
    sa.Column('writer', sa.String(length=100), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idx')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board')
    ### end Alembic commands ###
